/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SwapRouteImport } from './routes/swap'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SendRouteImport } from './routes/send'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MarketRouteImport } from './routes/market'
import { Route as DropsRouteImport } from './routes/drops'
import { Route as CreateRouteImport } from './routes/create'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarketIdRouteImport } from './routes/market.$id'

const SwapRoute = SwapRouteImport.update({
  id: '/swap',
  path: '/swap',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SendRoute = SendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const DropsRoute = DropsRouteImport.update({
  id: '/drops',
  path: '/drops',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketIdRoute = MarketIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MarketRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/create': typeof CreateRoute
  '/drops': typeof DropsRoute
  '/market': typeof MarketRouteWithChildren
  '/profile': typeof ProfileRoute
  '/send': typeof SendRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/swap': typeof SwapRoute
  '/market/$id': typeof MarketIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/create': typeof CreateRoute
  '/drops': typeof DropsRoute
  '/market': typeof MarketRouteWithChildren
  '/profile': typeof ProfileRoute
  '/send': typeof SendRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/swap': typeof SwapRoute
  '/market/$id': typeof MarketIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/create': typeof CreateRoute
  '/drops': typeof DropsRoute
  '/market': typeof MarketRouteWithChildren
  '/profile': typeof ProfileRoute
  '/send': typeof SendRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/swap': typeof SwapRoute
  '/market/$id': typeof MarketIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/create'
    | '/drops'
    | '/market'
    | '/profile'
    | '/send'
    | '/sitemap.xml'
    | '/swap'
    | '/market/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/create'
    | '/drops'
    | '/market'
    | '/profile'
    | '/send'
    | '/sitemap.xml'
    | '/swap'
    | '/market/$id'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/create'
    | '/drops'
    | '/market'
    | '/profile'
    | '/send'
    | '/sitemap.xml'
    | '/swap'
    | '/market/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  CreateRoute: typeof CreateRoute
  DropsRoute: typeof DropsRoute
  MarketRoute: typeof MarketRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  SendRoute: typeof SendRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SwapRoute: typeof SwapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/swap': {
      id: '/swap'
      path: '/swap'
      fullPath: '/swap'
      preLoaderRoute: typeof SwapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send': {
      id: '/send'
      path: '/send'
      fullPath: '/send'
      preLoaderRoute: typeof SendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drops': {
      id: '/drops'
      path: '/drops'
      fullPath: '/drops'
      preLoaderRoute: typeof DropsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market/$id': {
      id: '/market/$id'
      path: '/$id'
      fullPath: '/market/$id'
      preLoaderRoute: typeof MarketIdRouteImport
      parentRoute: typeof MarketRoute
    }
  }
}

interface MarketRouteChildren {
  MarketIdRoute: typeof MarketIdRoute
}

const MarketRouteChildren: MarketRouteChildren = {
  MarketIdRoute: MarketIdRoute,
}

const MarketRouteWithChildren =
  MarketRoute._addFileChildren(MarketRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  CreateRoute: CreateRoute,
  DropsRoute: DropsRoute,
  MarketRoute: MarketRouteWithChildren,
  ProfileRoute: ProfileRoute,
  SendRoute: SendRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SwapRoute: SwapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
